<a href="https://colab.research.google.com/github/SaachiSuvarna/NNdl-lab/blob/main/Next_word_Prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install tensorflow

RNN->Recurrent Neural network
For textual prediction,sentiment analysis----For fututre prediction
1.The text(Movie was bad)
2.Corpus/Dictionary:[m,w,b]
3.Vectorized format:[1000]--means there is the word movie


In [3]:
import tensorflow as tf
import numpy as np

In [4]:
text="this is a sample text used to demonstrate predictive text with basic rnn.In, this example we will predict the next word as you type."

In [5]:
tokenizer=tf.keras.layers.TextVectorization()
tokenizer.adapt(text.split())

In [6]:
text_sequence=tokenizer(text)
text_sequence

<tf.Tensor: shape=(13,), dtype=int64, numpy=array([ 6, 10, 13,  7,  2,  4,  5, 11,  9,  2,  3, 12,  8])>

In [7]:
x=text_sequence[:-1]
y=text_sequence[1:]

In [8]:
model=tf.keras.Sequential([
    tf.keras.layers.Embedding(input_dim=len(tokenizer.get_vocabulary()),output_dim=64,input_length=1),
    tf.keras.layers.SimpleRNN(128,return_sequences=True),
    tf.keras.layers.Dense(len(tokenizer.get_vocabulary()),activation='softmax')
])

In [9]:
model.compile(loss='sparse_categorical_crossentropy',optimizer='adam')

In [10]:
model.fit(x,y,epochs=50)

Epoch 1/50
1/1 [==============================] - 2s 2s/step - loss: 2.6457
Epoch 2/50
1/1 [==============================] - 0s 15ms/step - loss: 2.6288
Epoch 3/50
1/1 [==============================] - 0s 12ms/step - loss: 2.6120
Epoch 4/50
1/1 [==============================] - 0s 14ms/step - loss: 2.5952
Epoch 5/50
1/1 [==============================] - 0s 11ms/step - loss: 2.5784
Epoch 6/50
1/1 [==============================] - 0s 11ms/step - loss: 2.5615
Epoch 7/50
1/1 [==============================] - 0s 12ms/step - loss: 2.5444
Epoch 8/50
1/1 [==============================] - 0s 11ms/step - loss: 2.5272
Epoch 9/50
1/1 [==============================] - 0s 10ms/step - loss: 2.5098
Epoch 10/50
1/1 [==============================] - 0s 12ms/step - loss: 2.4920
Epoch 11/50
1/1 [==============================] - 0s 11ms/step - loss: 2.4739
Epoch 12/50
1/1 [==============================] - 0s 16ms/step - loss: 2.4554
Epoch 13/50
1/1 [==============================] - 0s 11ms/step

In [13]:
def generate_next_word(seed_text):
  seed_sequence=tokenizer(seed_text)
  predicted_prob=model.predict(seed_sequence)
  predicted_index=np.argmax(predicted_prob)
  predicted_word=tokenizer.get_vocabulary()[predicted_index]
  return predicted_word

In [14]:
input_text="used"
predicted_word=generate_next_word(input_text)
print(f"Input: '{input_text}',Predicted:'{predicted_word}'")

1/1 [==============================] - 0s 212ms/step
Input: 'used',Predicted:'to'


USING LSTM MODEL


In [15]:
import tensorflow as tf
import numpy as np

In [17]:
text="this is a sample text used to demonstrate predictive text with basic rnn.In, this example we will predict the next word as you type."

In [18]:
tokenizer=tf.keras.layers.TextVectorization()
tokenizer.adapt(text.split())

In [19]:
text_sequence=tokenizer(text)
text_sequence




<tf.Tensor: shape=(24,), dtype=int64, numpy=
array([ 2, 18, 23, 13,  3,  9, 11, 20, 15,  3,  6, 21, 14,  2, 19,  8,  7,
       16, 12, 17,  5, 22,  4, 10])>

In [20]:
x=text_sequence[:-1]
y=text_sequence[1:]

model=tf.keras.Sequential([
    tf.keras.layers.Embedding(input_dim=len(tokenizer.get_vocabulary()),output_dim=64,input_length=1),
    tf.keras.layers.LSTM(128,return_sequences=True),
    tf.keras.layers.Dense(len(tokenizer.get_vocabulary()),activation='softmax')
])

In [21]:
model.compile(loss='sparse_categorical_crossentropy',optimizer='adam')

model.fit(x,y,epochs=50)

Epoch 1/50
1/1 [==============================] - 4s 4s/step - loss: 3.1781
Epoch 2/50
1/1 [==============================] - 0s 14ms/step - loss: 3.1754
Epoch 3/50
1/1 [==============================] - 0s 12ms/step - loss: 3.1727
Epoch 4/50
1/1 [==============================] - 0s 24ms/step - loss: 3.1700
Epoch 5/50
1/1 [==============================] - 0s 14ms/step - loss: 3.1673
Epoch 6/50
1/1 [==============================] - 0s 12ms/step - loss: 3.1646
Epoch 7/50
1/1 [==============================] - 0s 13ms/step - loss: 3.1618
Epoch 8/50
1/1 [==============================] - 0s 15ms/step - loss: 3.1589
Epoch 9/50
1/1 [==============================] - 0s 16ms/step - loss: 3.1560
Epoch 10/50
1/1 [==============================] - 0s 14ms/step - loss: 3.1531
Epoch 11/50
1/1 [==============================] - 0s 12ms/step - loss: 3.1500
Epoch 12/50
1/1 [==============================] - 0s 19ms/step - loss: 3.1469
Epoch 13/50
1/1 [==============================] - 0s 17ms/step

In [22]:
def generate_next_word(seed_text):
  seed_sequence=tokenizer(seed_text)
  predicted_prob=model.predict(seed_sequence)
  predicted_index=np.argmax(predicted_prob)
  predicted_word=tokenizer.get_vocabulary()[predicted_index]
  return predicted_word

In [23]:
input_text="used"
predicted_word=generate_next_word(input_text)
print(f"Input: '{input_text}',Predicted:'{predicted_word}'")

1/1 [==============================] - 1s 1s/step
Input: 'used',Predicted:'to'


In [ ]:
from google.colab import drive
drive.mount('/content/drive')